OPTI2SMPL = {
    "Hip": 0,
    "RThigh": 1,
    "LThigh": 2,
    "Ab": 3,
    "RShin": 4,
    "LShin": 5,
    # "" : 6,
    "RFoot": 7,
    "LFoot": 8,
    "Chest": 9,
    "RToe": 10,
    "LToe": 11,
    "Neck": 12,
    "RShoulder": 13,
    "LShoulder": 14,
    "Head": 15,
    "RUArm": 16,
    "LUArm": 17,
    "RFArm": 18,
    "LFArm": 19,
    "RHand": 20,
    "LHand": 21,
    # "" : 22,
    # "" : 23,
}

# OPTI2SMPLH = {
#         "RRing1" : ,
#         "LPinky3" : ,
#         "RShin" : ,
#         "LShoulder" : ,
#         "RRing2" : ,
#         "RRing3":,
#         "RPinky1":,
#         "RUArm":,
#         "LFoot":,
#         "Chest":,
#         "LPinky1":,
#         "LPinky2":,
#         "RIndex2":,
#         "LThumb1":,
#         "RMiddle1":,
#         "LRing2":,
#         "RFoot":,
#         "LIndex1":,
#         "LIndex3":,
#         "RFArm":,
#         "RThumb1":,
#         "RShoulder":,
#         "RIndex3":,
#         "RThigh":,
#         "Head":,
#         "LThumb2":,
#         "LMiddle3":,
#         "Neck":,
#         "LMiddle2":,
#         "RThumb3":,
#         "RHand":,
#         "LRing3":,
#         "LRing1":,
#         "RMiddle3":,
#         "RPinky3":,
#         "Ab":,
#         "RIndex1":,
#         "LThumb3":,
#         "LIndex2":,
#         "RToe":,
#         "LThigh":,
#         "LHand":,
#         "RThumb2":,
#         "RMiddle2":,
#         "LUArm":,
#         "RPinky2":,
#         "LToe":,
#         "Hip":,
#         "LShin":,
#         "LMiddle1":,
# "LFArm":,
# }

MANUS2MANO = {
    "Hand": 0,
    "Index_MCP": 1,
    "Index_PIP": 2,
    "Index_DIP": 3,
    "Middle_MCP": 4,
    "Middle_PIP": 5,
    "Middle_DIP": 6,
    "Pinky_MCP": 7,
    "Pinky_PIP": 8,
    "Pinky_DIP": 9,
    "Ring_MCP": 10,
    "Ring_PIP": 11,
    "Ring_DIP": 12,
    "Thumb_CMC": 13,
    "Thumb_MCP": 14,
    "Thumb_DIP": 15,
}

