OPTI2SMPL = {
    "Hip": 0,
    "LThigh": 1,
    "RThigh": 2,
    "Ab": 3,
    "LShin": 4,
    "RShin": 5,
    # "" : 6,
    "LFoot": 7,
    "RFoot": 8,
    "Chest": 9,
    "LToe": 10,
    "RToe": 11,
    "Neck": 12,
    "LShoulder": 13,
    "RShoulder": 14,
    "Head": 15,
    "LUArm": 16,
    "RUArm": 17,
    "LFArm": 18,
    "RFArm": 19,
    "LHand": 20,
    "RHand": 21,
    # "" : 22,
    # "" : 23,
}

OPTI2SMPLH = {
    # Body Joints
    "Hip": 0,
    "LThigh": 1,
    "RThigh": 2,
    "Spine1": 3,
    "LKnee": 4,
    "RKnee": 5,
    "Spine2": 6,
    "LAnkle": 7,
    "RAnkle": 8,
    "Spine3": 9,
    "LFoot": 10,
    "RFoot": 11,
    "Neck": 12,
    "LCollar": 13,
    "RCollar": 14,
    "Head": 15,
    "LShoulder": 16,
    "RShoulder": 17,
    "LElbow": 18,
    "RElbow": 19,
    "LWrist": 20,
    "RWrist": 21,

    # Left Hand Joints
    "LHand": 22,
    "LIndex1": 23,
    "LIndex2": 24,
    "LIndex3": 25,
    "LMiddle1": 26,
    "LMiddle2": 27,
    "LMiddle3": 28,
    "LPinky1": 29,
    "LPinky2": 30,
    "LPinky3": 31,
    "LRing1": 32,
    "LRing2": 33,
    "LRing3": 34,
    "LThumb1": 35,
    "LThumb2": 36,

    # Right Hand Joints
    "RHand": 37,
    "RIndex1": 38,
    "RIndex2": 39,
    "RIndex3": 40,
    "RMiddle1": 41,
    "RMiddle2": 42,
    "RMiddle3": 43,
    "RPinky1": 44,
    "RPinky2": 45,
    "RPinky3": 46,
    "RRing1": 47,
    "RRing2": 48,
    "RRing3": 49,
    "RThumb1": 50,
    "RThumb2": 51,
}

MANUS2MANO = {
    "Hand": 0,
    "Index_MCP": 1,
    "Index_PIP": 2,
    "Index_DIP": 3,
    "Middle_MCP": 4,
    "Middle_PIP": 5,
    "Middle_DIP": 6,
    "Pinky_MCP": 7,
    "Pinky_PIP": 8,
    "Pinky_DIP": 9,
    "Ring_MCP": 10,
    "Ring_PIP": 11,
    "Ring_DIP": 12,
    "Thumb_CMC": 13,
    "Thumb_MCP": 14,
    "Thumb_DIP": 15,
}

# SMPL-X mapping: Maps OptiTrack joint names to (tensor_name, index)
OPTI2SMPLX = {
    # Body Joints (mapped to body_pose tensor)
    "Hip": ("global_orient", 0),
    "LThigh": ("body_pose", 0),
    "RThigh": ("body_pose", 1),
    "Ab": ("body_pose", 2),
    "LShin": ("body_pose", 3),
    "RShin": ("body_pose", 4),
    "Chest": ("body_pose", 5),
    "LFoot": ("body_pose", 6),
    "RFoot": ("body_pose", 7),
    # Spine3 maps to index 8
    "LToe": ("body_pose", 9),
    "RToe": ("body_pose", 10),
    "Neck": ("body_pose", 11),
    "LShoulder": ("body_pose", 12),  # Left Collar
    "RShoulder": ("body_pose", 13),  # Right Collar
    "Head": ("body_pose", 14),
    "LUArm": ("body_pose", 15),
    "RUArm": ("body_pose", 16),
    "LFArm": ("body_pose", 17),
    "RFArm": ("body_pose", 18),
    "LHand": ("body_pose", 19), # Left Wrist
    "RHand": ("body_pose", 20), # Right Wrist

    # Left Hand (mapped to left_hand_pose tensor)
    "LIndex1": ("left_hand_pose", 1),
    "LIndex2": ("left_hand_pose", 2),
    "LIndex3": ("left_hand_pose", 3),
    "LMiddle1": ("left_hand_pose", 4),
    "LMiddle2": ("left_hand_pose", 5),
    "LMiddle3": ("left_hand_pose", 6),
    "LPinky1": ("left_hand_pose", 7),
    "LPinky2": ("left_hand_pose", 8),
    "LPinky3": ("left_hand_pose", 9),
    "LRing1": ("left_hand_pose", 10),
    "LRing2": ("left_hand_pose", 11),
    "LRing3": ("left_hand_pose", 12),
    "LThumb1": ("left_hand_pose", 13),
    "LThumb2": ("left_hand_pose", 14),
    "LThumb3": ("left_hand_pose", 15),

    # Right Hand (mapped to right_hand_pose tensor)
    "RIndex1": ("right_hand_pose", 1),
    "RIndex2": ("right_hand_pose", 2),
    "RIndex3": ("right_hand_pose", 3),
    "RMiddle1": ("right_hand_pose", 4),
    "RMiddle2": ("right_hand_pose", 5),
    "RMiddle3": ("right_hand_pose", 6),
    "RPinky1": ("right_hand_pose", 7),
    "RPinky2": ("right_hand_pose", 8),
    "RPinky3": ("right_hand_pose", 9),
    "RRing1": ("right_hand_pose", 10),
    "RRing2": ("right_hand_pose", 11),
    "RRing3": ("right_hand_pose", 12),
    "RThumb1": ("right_hand_pose", 13),
    "RThumb2": ("right_hand_pose", 14),
    "RThumb3": ("right_hand_pose", 15),
}